project:
  type: website
  output-dir: docs

website:
  title: "Yellow Island 2023"
  navbar:
    left:
      - href: index.qmd
        text: Skill Building
      - href: index.qmd
        text: Reading
      - href: index.qmd
        text: Professional Development
      - href: index.qmd
        text: Mental Health

format:
  html:
    theme: solarized
    css: styles.css
    toc: true

editor: visual
