project:
  type: website
  output-dir: docs

website:
  title: "Yellow Island 2023"
  navbar:
    left:
      - href: index.qmd
        text: Schedule
      - href: index.qmd
        text: REU
      - href: index.qmd
        text: DDCSP
      - href: index.qmd
        text: Resources

format:
  html:
    theme: solarized
    css: styles.css
    toc: true

editor: visual
