---
title: "dada2 with OG fastq files"
author: "Chris"
date: "2024-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load packages
```{r}

if(!requireNamespace("BiocManager")){
  install.packages("BiocManager")
}
BiocManager::install("phyloseq")

```

```{r}

## try http:// if https:// URLs are not supported
if (!requireNamespace("BiocManager", quietly=TRUE))
    install.packages("BiocManager")
BiocManager::install("dada2", version= "3.18")

packageVersion("dada2")


```

# load packages
```{r}

library("phyloseq")
library("dada2")

```

# read in sequences
```{r}

getwd()

path <- "/Users/cmantegna/Desktop/ysequences" 
fnFs <- sort(list.files(path, pattern = "_R1_001.fastq.gz", full.names = TRUE))
fnRs <- sort(list.files(path, pattern = "_R2_001.fastq.gz", full.names = TRUE))

```

# find the missing reverse read
```{r}

# get sample names for each by removing the ending
sampleNamesFs <- gsub("_R1_001.fastq.gz", "", basename(fnFs))
sampleNamesRs <- gsub("_R2_001.fastq.gz", "", basename(fnRs))

# find the missing one
missingReverse <- setdiff(sampleNamesFs, sampleNamesRs)

# result
print(missingReverse)

```


```{r}

filtFs <- file.path(path, "filtered", basename(fnFs))
filtRs <- file.path(path, "filtered", basename(fnRs))
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(240,160),
                     maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
                     compress=TRUE, multithread=TRUE)

```

